### ISSUE TITLE
feature request add optionaltonullsafeoperator

### ISSUE THREAD

**Issue by chrillep** [hammer-tools/php-hammer#1]
https://github.com/driftingly/rector-laravel/blob/main/docs/rector_rules_overview.md#optionaltonullsafeoperatorrector

OptionalToNullsafeOperatorRector
Convert simple calls to optional helper to use the nullsafe operator

🔧 configure it!

class: [Rector\Laravel\Rector\PropertyFetch\OptionalToNullsafeOperatorRector](https://github.com/driftingly/rector-laravel/blob/main/src/Rector/PropertyFetch/OptionalToNullsafeOperatorRector.php)

```php
use Rector\Config\RectorConfig;
use Rector\Laravel\Rector\PropertyFetch\OptionalToNullsafeOperatorRector;

return static function (RectorConfig $rectorConfig): void {
    $rectorConfig->ruleWithConfiguration(OptionalToNullsafeOperatorRector::class, [
        OptionalToNullsafeOperatorRector::EXCLUDE_METHODS => ['present'],
    ]);
};
```
↓
```diff
-optional($user)->getKey();
-optional($user)->id;
+$user?->getKey();
+$user?->id;
 // macro methods
 optional($user)->present()->getKey();
 ```
 
 
 was but is probably not limited to laravel framwork
 
https://github.com/laravel/framework/blob/cd7f19d3e4c09c170bef13663aad96077c201789/src/Illuminate/Support/Optional.php#L1-L131 
 
https://github.com/laravel/framework/blob/4d126e876d42d8549c420f451badc61a45b6809a/src/Illuminate/Support/helpers.php#L181-L197
 
 relates to:
 https://github.com/hammer-tools/laravel-hammer/issues/1

**Comment by rentalhost** [comment]
@chrillep could you explain to me what this macro method means (` optional($user)->present()->getKey()`)? How should be the reaction of the inspection be in this case?

**Comment by rentalhost** [comment]
Fixed by https://github.com/hammer-tools/php-hammer/releases/tag/0.18.0

You can either download the release package and install it manually or wait for Jetbrains to propagate, which usually takes 1-3 days.

**Comment by chrillep** [comment]
ty ill have a look

**Comment by chrillep** [comment]
<img width="554" alt="Skärmavbild 2022-11-10 kl  12 05 41" src="https://user-images.githubusercontent.com/1267931/201075237-1909b406-da5d-4765-87b4-f0e7e5fb38d7.png">



not installable maybe due to version constraint eap.

https://plugins.jetbrains.com/plugin/19515-php-hammer/versions

<img width="977" alt="Skärmavbild 2022-11-10 kl  12 06 23" src="https://user-images.githubusercontent.com/1267931/201075379-42c9abba-9e44-4f25-8c2e-3509146fcaa5.png">

**Comment by chrillep** [comment]
im not on eap yet :(

**Comment by rentalhost** [comment]
@chrillep Nice! Unfortunately there are some changes to the Jetbrains API compared to the stable version. So I had to update it to EAP. But it seems to me that very soon we will have a final non-EAP update.

**Comment by chrillep** [comment]
WORKS LIKE A CHARM! much love! ❤️ 
small thing great dx! 

after all native supported stuff is usually better

<img width="629" alt="Skärmavbild 2022-12-06 kl  09 23 09" src="https://user-images.githubusercontent.com/1267931/205858804-110404b0-6d43-4507-98c1-13dc6bba75b9.png">
