### ISSUE TITLE
Inspection "Parameter is implicitly nullable" and short syntax style type.

### ISSUE THREAD

**Issue by kaliberx** [hammer-tools/php-hammer#19]
The inspection for language level >= 8.0 suggest adding null type.

For ```function save(int $x = null)``` it suggest ```function save(int|null $x = null)```.
Is there a way to change the behawior to suggest ```function save(?int $x = null)``` and make it working for language level >= 7.1?

**Comment by rentalhost** [comment]
Indeed, currently, the inspection only occurs when the language level is >= 8.0 and supports only the standard `int|null` format. Another inspection will help normalize to `?int`.

Your suggestions are relevant: to allow users to choose the format (`?int` for PHP >= 7.1 and `int|null` for PHP >= 8.0, if available).

I will implement this in the next plugin update.

Thank you for your valuable input!

**Comment by rentalhost** [comment]
Thank you for taking the time to suggest this improvement. The update has been implemented in version 0.23.0 and is available on the **[Releases](https://github.com/hammer-tools/php-hammer/releases)** page. It will soon be accessible on the JetBrains Marketplace, allowing you to directly update through PhpStorm.

A new option has been added to the **Parameter is implicitly nullable** inspection, enabling you to choose the auto-fix format, either the short format (`?int`) or the long format (`int|null`), which will be the _default_. However, for PHP versions lower than 8.0, the short format will be automatically enforced without the need to adjust this setting per project version.

Please note that this configuration might overlap with other inspections performing similar actions. Consequently, you might need to apply the same configuration, based on your preferred format, to other inspections performing similar modifications, one by one.
