### ISSUE TITLE
Parameter defaults to null doesn't always make sense

### ISSUE THREAD

**Issue by DrowningElysium** [hammer-tools/php-hammer#2]
![image](https://user-images.githubusercontent.com/9342313/200399727-9e547933-4d9e-464d-83f7-ef7affa81c9c.png)

https://github.com/hammer-tools/php-hammer/wiki/Inspections#parameter-defaults-to-null

I think in this case it doesn't make much sense to make it nullable. Wouldn't it be better to check that there are multiple variables with a default instead?

**Comment by rentalhost** [comment]
@DrowningElysium the idea of this inspection is that methods or functions never define default values (except `null`). So in your case it could work like this:

```php
public function list(int|null $page = null): array {
    $page ??= 1;
    /** ... */
}
```

This methodology may not make sense for methods that are not intended to be modified in the future, but imagine the following situation: today your `list(int $page = 1)` method looks exactly like this, and if you don't specify `$page` then its value will be `1`, which is expected (eg. just `->list()`).

So imagine that you've made use of this method over and over by the system (without arguments), and in the future you decide to add a second parameter, like `list(int $page = 1, Filter $filter = null)`. To use it, you will either have to set the value of `$page`, which is `1`, or else you will have to make `$page = null`, so you can call `->list(null, $filter)` like intended.

However, I'm convinced that maybe we can ignore simple situations, like functions that have a single optional argument, like your example, as it would easily be possible to convert them in the future, like in the example above. However, I would like to keep this option as optional. What do you think?

**Comment by asgraf** [comment]
I think case with boolean arguments does not make sense even more
```php
public function someFunction(bool $doSomeExtraThing = false)
```

**Comment by rentalhost** [comment]
This weekend I will try to work on these modifications and put them as optional. :)
