### ISSUE TITLE
Using array_merge() to renumber/reindex array

### ISSUE THREAD

**Issue by reedy** [hammer-tools/php-hammer#22]
I'm not sure how common of a use case this is (but I've found a few inside MediaWiki and hosted extensions)...

I know it is already a weak warning.

But calling `array_merge` with only one parameter is a way to renumber the array, for example https://github.com/wikimedia/mediawiki/blob/0077c5d/tests/phpunit/includes/api/query/ApiQueryTestBase.php#L150-L153

May be a invalid request.

There's cases (that I've fixed) where someone is doing `array_merge( [ 'foo' ] )` (ie constructing the array inside the function call, not just passing an existing variable) that were indeed more than valid...

**Comment by rentalhost** [comment]
Hm... And would there be any difference between using `array_merge()` vs `array_values()` in this case?

**Comment by reedy** [comment]
> Hm... And would there be any difference between using `array_merge()` vs `array_values()` in this case?

Not sure, will check. It would certainly be more obvious to make use of `array_values()`

**Comment by rentalhost** [comment]
I'm closing this report. If you manage to find an example that illustrates what you mentioned, I'd be happy to investigate and work on implementing the best solution.
