### ISSUE TITLE
"string can be replaced by ::class equivalent" false positive

### ISSUE THREAD

**Issue by reedy** [hammer-tools/php-hammer#23]
" string can be replaced by ::class equivalent" should (try to look) look if the suggested class exists, otherwise the replacement might not actually work.

For example:

```php
class_alias( BadFileLookup::class, 'MediaWiki\\BadFileLookup' );
```

![Screenshot 2023-08-22 at 19 48 49](https://github.com/hammer-tools/php-hammer/assets/67615/d44ed5f8-f055-4621-a66f-2dd6782ab099)

into

```
class_alias( BadFileLookup::class, MediaWiki\\BadFileLookup::class );
```

![Screenshot 2023-08-22 at 19 48 59](https://github.com/hammer-tools/php-hammer/assets/67615/19776e0e-619e-421b-b9fa-21466253b39e)

**Comment by reedy** [comment]
I'm confusing two issues here, never mind I didn't fix the `\` in the name.

**Comment by rentalhost** [comment]
Yes, if my memory serves me correctly, PHP always determines the full name of the class, even if it doesn't exist. For example, `Abc\Abc::class` will always return `"\Abc\Abc"`, even if this class does not exist in the code (and also via respecting the namespace, if it does).
