### ISSUE TITLE
Autofix not keeping whitespace?

### ISSUE THREAD

**Issue by reedy** [hammer-tools/php-hammer#26]
I'm not sure offhand if this a bug with the plugin, or my PhpStorm style config (as I'm still on a "new" computer without a tuned PhpStorm config)...  If it is the config, it's a little odd that it's not reformatting the whole line, and as such, removing other spaces...

But the autofix for "Anonymous function cab be static" shouldn't be replacing `fn ( $` with `static fn ($`

https://gerrit.wikimedia.org/r/c/mediawiki/core/+/951557/2/tests/phpunit/includes/auth/LocalPasswordPrimaryAuthenticationProviderTest.php

**Comment by rentalhost** [comment]
I think I misunderstood this one too. I applied it to the original code and the result seemed correct. Do you have a screenshot of something more specific?

**Comment by reedy** [comment]
![Screenshot 2023-08-23 at 15 08 28](https://github.com/hammer-tools/php-hammer/assets/67615/dad6a26b-eae5-4e65-9854-c847602146c4)

^ From the diff...

I think this might be a style config as I mentioned; I think a completely different autofix (not from PHP Hammer) did it too. Will try and test it more thoroughly...

**Comment by reedy** [comment]
Yup, seems it was that. Just was some weird changes.
