### ISSUE TITLE
Support PS-233.*

### ISSUE THREAD

**Issue by reedy** [hammer-tools/php-hammer#30]
>Plugin 'PHP Hammer' (version '0.23.0') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is PS-233.8264.9

**Comment by rentalhost** [comment]
Nice! I will try to update today.

**Comment by rentalhost** [comment]
Thank you for taking the time to report this issue. The fix has been implemented in version **0.24.0** and is available on the **[Releases](https://github.com/hammer-tools/php-hammer/releases)** page for manual installation. Alternatively, you can wait for the official release on the **JetBrains Marketplace**, which should happen in approximately 3 days.

- **In response to the issue you mentioned:** Thank you for promptly notifying us about the new EAP; I wasn't aware it had been released. The version released today should work well with both the latest stable version and the new EAP.
