### ISSUE TITLE
Smart replace with "null" on `readonly`

### ISSUE THREAD

**Issue by asgraf** [hammer-tools/php-hammer#33]
Example:
```php
class SomeClass
{
    public function __construct(private readonly $variable = 'default') {
    }
}
```
Applying `Smart replace with "null"` generates invalid code because `readonly` means its value cannot be changed after initialization and the `??=` operator will generate error
In this case skip inspection for `readonly` arguments

**Comment by asgraf** [comment]
Related issue #32

**Comment by rentalhost** [comment]
Thank you for your time in reporting this issue. The fix has been implemented in **version 0.25.0** and is **available exclusively** through the [**Releases**](https://github.com/hammer-tools/php-hammer/releases) page. It will be implemented in the JetBrains Marketplace once [**this issue**](https://github.com/hammer-tools/php-hammer/issues/10) that are affecting some users are resolved (no ETA).

**In response to your report:**

- The issue has been identified and fixed. Now, it will no longer suggest using `null` when the promoted property is `readonly`. I've proposed an idea to make this possible to the PHP team, but I don't think it will go very far (https://github.com/php/php-src/issues/12452).

**Comment by damianwadley** [comment]
Speaking "off-the-record" as a follow-up to that report, my recommendation is either:

(a) To not use a promoted property in the case where you need a non-null default value. Promoted properties aren't meant to be a replacement to defined properties, but merely shorthand to save developers from the boilerplate code of

```php
public function __construct(int $a, int $b, int $c, int $d) {
    $this->a = $a;
    $this->b = $b;
 }`. Personally, I don't mix promoted and non-promoted properties in a class as that makes it harder to read the code: "I know there's an assignment to a property but I don't see it in the list of defined properties?" and such. It's much more suitable for "data purse"-type classes.

(b) To leave the default value as null and to apply the special logic at the time the value is needed. This has a significant benefit of allowing the property to retain its "default value"-ness; in this example, if the property has a value of `123` then you've lost (even if intentionally) the ability to distinguish between it having that value explicitly vs. it not having a value provided and you applying a default in its place. I also like this as it moves the concept of the default value to the location where the default actually has meaning: the place it's being used, whereas the constructor should have as little logic (business-wise or code-wise) as possible.

Unsurprisingly, the latter is what I would do myself.

**Comment by rentalhost** [comment]
If I understand correctly, I agree with you to some extent. If I've understood it correctly, it's precisely the concept that `0` and `null` are _distinct and individually important values_ (where null means the absence of information, and 0 essentially means the value zero). However, the plugin suggests only when `int` is an acceptable value on its own, making it `null` to apply the "default" rule. But for cases where a distinction needs to be made, it should be done with caution. I prefer the application in the constructor, which, although I agree should be straightforward, is the best place to ensure that the entire application will respect the rule, and it wouldn't be necessary to use `??` all the time, for example (if that's what I understood from case B).

**Comment by damianwadley** [comment]
Yes, you're right. I'm thinking with more of a purist sense of design, and what you need here is something more practical - and something not as enthusiastic about making big changes to someone's code, too. And while I like the idea of preserving that "default value"-ness, I'll admit that it's just not something that ever really matters.

Demoting to a normal parameter is probably going to be the best solution for resolving the underlying issue of using a non-null default, as you've already considered. It's a little bit more intrusive, too, but I'll leave that to your judgment 👍
