### ISSUE TITLE
Suggestion: compact() style inspection and/or improve autofix for 'Replace with compact()'

### ISSUE THREAD

**Issue by tminich** [hammer-tools/php-hammer#36]
Personally I try to use named arguments whenever possible so, in consequence, I prefer to use the single argument array method of calling compact (`compact(var_name: ['a', 'b'])` instead of `compact('a', 'b')`).
It would be nice if PHP Hammer had an inspection for that or at least let me choose on the 'Replace with compact()' which one to use for quick-fix.

**Comment by rentalhost** [comment]
Thank you for your time in reporting this suggestion. It is implemented in **version 0.26.0** and is available through the [**Releases**](https://github.com/hammer-tools/php-hammer/releases) page. This update will be available on the **Jetbrains Market** in approximately three days if you prefer to wait.

**In response to your report:**

- The suggestion has been implemented as a new option for this inspection. You can now choose whether the quick-fix generates _positional arguments_ (as it's the default) or _named arguments_ (as you suggested).
