### ISSUE TITLE
Feature request: `#[SensitiveParameter]` inspection

### ISSUE THREAD

**Issue by asgraf** [hammer-tools/php-hammer#41]
Simple PHP 8.0+ inspection that suggests adding `#[SensitiveParameter]` to function arguments with specific name.
This attribute is used to mark a parameter that is sensitive and should have its value redacted if present in a stack trace. 

Example:
```php
function example($user, $password) {
//some code
}
```
Inspection should suggest change to:
```php
function example($user, #[SensitiveParameter] $password) {
//some code
}
```
I think that by default this list should contain names like:
- password, passwd (* passw *)
- password_hash, passwordHash (* hash)
- token, api_token, access_token, user_token (token *)
- secret, client_secret (* secret *)
- auth, auth_code (* auth *)
- api_key, apiKey, apikey, public_key, publicKey, publickey, private_key, privateKey, privatekey, encryption_key (*key)
- card, credit_card, creditCard, creditcard (* card)
- bank_account (* bank *)
- ccn
- pin
- jwt 
- cert
- email, mail
- phone
- first_name, firstname, firstName
- last_name, lastname, lastName
- full_name, fullname, fullName
- session, session_id

List of argument names to trigger on should be configurable by user so they could add/remove cases

**Comment by rentalhost** [comment]
The idea is very good, if you have more knowledge about other attributes, please send all the ideas you can. It's something new to me, but I know it's important, just like the idea reported in #39.

**Comment by rentalhost** [comment]
Thank you for taking the time to suggest this improvement. The implementation has been completed in **version 0.28.0** and is now available through the [**Releases**](https://github.com/hammer-tools/php-hammer/releases) page. If you prefer, this update will also be accessible on the **Jetbrains Market** in approximately three days.

**Regarding the specific topic:**

- I'd introduced a new inspection to notify you about the use of _sensitive names in parameters_. Honestly, I thought this would be a lot easier, but it was quite a challenge! There are two available options: the _list of sensitive words_ (which will automatically pluralize, so you only need to add `password`, for instance, and it will automatically recognize `passwords` as a sensitive word); and the second option, _enabled by default_, allows it to ignore `bool`, `int`, and `float` types (and _nullables_), even when they include sensitive words (e.g., `int $secret` won't trigger a notification).
