### ISSUE TITLE
PHP Attribute ideas

### ISSUE THREAD

**Issue by asgraf** [hammer-tools/php-hammer#42]
> if you have more knowledge about other attributes, please send all the ideas you can

You might want to check this links below for ideas

List of build-in php attributes (as to date):
https://www.exakat.io/en/php-native-attributes-quick-reference/

List of custom phpstorm attributes:
https://github.com/JetBrains/phpstorm-attributes/

Useful Enum php library that make use of custom attributes:
https://github.com/archtechx/enums#metadata

**Comment by asgraf** [comment]
You don't need to limit yourself to existing attributes you may want to invent your own custom PHP hammer attributes

**Comment by rentalhost** [comment]
Thank you for the suggestion. It seems that the main ones are already supported by the plugin now. I'm not sure if I should create custom attributes for the plugin, but it's now a possibility. Perhaps something interesting might come up in the future.
