### ISSUE TITLE
`#[\Override]` incorrectly reported illegal in traits

### ISSUE THREAD

**Issue by asgraf** [hammer-tools/php-hammer#44]
```php
abstract class A {
    function example() {
    //some code
    }
}

class B
{
    use ExampleOverrideTrait;
}

trait ExampleOverrideTrait
{
    #[\Override]//🔨 PHP Hammer: this method doesn't actually perform an override; remove this illegal #[Override] attribute.
    function example() {
        //some other code
    }
}
```

This is just not true. Even PhpStorm it self detects that `ExampleOverrideTrait::example()` overrides `A::example()` and allows quick navigation between them.

**Comment by rentalhost** [comment]
Damn, traits strike again!

**Comment by rentalhost** [comment]
Ah, yes... This is a case I believe might be a bit more complicated. In this particular case, the trait does indeed override, but what about when it doesn't? In other words: the trait is used in one class that does override and another that doesn't... I'm still thinking...

**Comment by asgraf** [comment]
If trait does not have `@mixin` phpdoc I think best approach would be to iterate over every class that uses this trait and and generate separate error for each including class.
If trait is not used in any class it should remain ignored.


However when trait has `@mixin` phpdoc this means trait this is intended for classes that extend/implement class/interface provided in `@mixin` phpdoc

**Comment by rentalhost** [comment]
@asgraf I'm attaching a preview. If possible, test it. It includes two improvements related to this, and I'll provide more details once I finish #43.

[php-hammer-0.29.0-preview.zip](https://github.com/hammer-tools/php-hammer/files/13135673/php-hammer-0.29.0-preview.zip)

If possible, also check if there are any specific cases where the inspection is failing, as it doesn't have anything related to @mixin at the moment, and perhaps this could be an issue. If possible, providing a sample code would be helpful.

**Comment by asgraf** [comment]
I tested this add-on on my code base. Results are very depended on the fact if trait is attached to at least one class.
Here are the findings:

**Test 1:
Tested on Traits that are not yet attached to any class**

- Every method with `#[Override]` displays `🔨 PHP Hammer: this method doesn't actually perform an override; remove this illegal `#[Override]` attribute.` error is displayed` 

**Suggestion**: do not trigger this inspection on `public`/`protected` methods of traits that are not attached to any class (unless `@mixin` is present)

- Every method without override displays `🔨 PHP Hammer: this method performs an override; consider using the #[Override] attribute.` This triggers even on `private` methods!!!

**Suggestion1**: never trigger this on `private` methods - by definition private method cannot be overridden so `#[Override]` is always invalid for them
**Suggestion2**: do not trigger this inspection on `public`/`protected` methods of traits that are not attached to any class (unless `@mixin` is present)

**Test 2:
I attached trait to 10 classes where parent has method with same name. Then added this trait to extra class where parent does not have method with same name to see what happens.**

- If all of classes (that trait is attached to) override parent method `#[\Override]` is not reported as invalid.
- If only one of those classes does not override parent method `🔨 PHP Hammer: this method doesn't actually perform an override; remove this illegal #[Override] attribute.` error is displayed. This error is unhelpful because does say which class (trait is attached to) causes this error

**Suggestion**: change error message to reflect which class (trait is attached to) causes this error

- Adding `#[\Override]` seem to be only suggested if in case of all of those trait method override takes place. If one of them doesn't override parent, adding `#[Override]` is not suggested.

**Suggestion**: in mixed cases when some attached classes do override parent and some don't i would show warning message because this suggest architectural error (trait is probably added to a wrong class by mistake)

**Comment by rentalhost** [comment]
**Test 1**

- I had a lot of thoughts regarding the issue of a `trait` not being used by any class yet: should it or should it not warn about the illegal use of `#[Override]`? In theory, it's an error that's impossible due to a "lack of evidence," so to speak. The problem would only have the potential to exist after the first practical use (or via `@mixin`, as suggested). In this case, by default, I'll ignore the unnecessary use of `#[Override]`, but this is now an option (disabled by default, so it will only ignore the inspection in cases like these by default).

- Regarding `@mixin`, I need a practical example because I don't usually use it, and I'm afraid of implementing something incorrectly in this regard.

- In terms of `#[Override]` on private methods, it is now treated as illegal by one inspection (meaning it suggests removing `#[Override]`) and is no longer suggested by the other inspection (meaning it is no longer suggested in almost-compatible cases, so to speak, except for the fact that it's a private method);

**Test 2**

- It makes sense. Now, the inspection will identify cases where `#[Override]` makes sense and when it doesn't. If there is an override applied correctly, then the issue lies with the class that didn't apply it correctly. As an intention action, I created two searches: one to display the methods where the override occurs correctly, and another to show the classes that used the trait but didn't create the override method. It will be up to the user whether they will correct or remove it.

---

I'm attaching another preview in case you want to test how it's coming along. You can also review the latest commits, which might make it easier to understand what has been done.

[php-hammer-0.29.0-preview.3.zip](https://github.com/hammer-tools/php-hammer/files/13210415/php-hammer-0.29.0-preview.3.zip)

**Comment by asgraf** [comment]
> Regarding @mixin, I need a practical example because I don't usually use it, and I'm afraid of implementing something incorrectly in this regard.

In regard to @mixin uses here is simple but real world example for CakePHP
All table objects in CakePHP extend `\Cake\ORM\Table` provided by CakePHP framework
This my simple custom trait that is intended to be applied to any table that happens to have `expires` field

```php
<?php
/**
 * @mixin \Cake\ORM\Table
 */
trait ExpiresTrait
{
    public function findActive(QueryInterface $query): QueryInterface
    {
        return $query->where([
            $this->getAlias() . '.expires > NOW()',
        ]);
    }

    public function findExpired(QueryInterface $query): QueryInterface
    {
        return $query->where([
            'OR' => [
                $this->getAlias() . '.expires <= NOW()',
                $this->getAlias() . '.expires IS NULL'
            ],
        ]);
    }

    /**
     * Finds all records that are expiring in 24 hours or less
     */
    public function findExpiry24h(QueryInterface $query): QueryInterface
    {
        return $query->where([
            'OR' => [
                $this->getAlias() . '.expires IS NULL',
                $this->getAlias() . '.expires <= NOW() + INTERVAL 24 HOUR',
            ],
        ]);
    }

    /**
     * Finds all records that are expired 2 weeks ago or more
     */
    public function findExpired2Weeks(QueryInterface $query): QueryInterface
    {
        return $query->where([
            'OR' => [
                $this->getAlias() . '.expires IS NULL',
                $this->getAlias() . '.expires <= NOW() - INTERVAL 2 WEEK',
            ]
        ]);
    }

    /**
     * Finds all records that are expiring in 30 days or less
     */
    public function findExpiry30d(QueryInterface $query): QueryInterface
    {
        return $query->where([
            'OR' => [
                $this->getAlias() . '.expires IS NULL',
                $this->getAlias() . '.expires <= NOW() + INTERVAL 30 DAY',
            ],
        ]);
    }
}
```

This ensures that PhpStorm wont complain about `$this->getAlias()` call even if this trait hasn't been applied yet to any class in this project

In this case `@mixin \Cake\ORM\Table` tells static analyzers: 
- you can assume that all methods and properties defined in `\Cake\ORM\Table` class will also exist in class that the trait will be applied to
- you cannot assume that trait will applied directly `\Cake\ORM\Table` class
- in real world use cases you can safely assume that trait will never applied directly to `\Cake\ORM\Table` class (this would be misuse of `@mixin` and bad practice)

More info:
https://freek.dev/1482-the-mixin-php-docblock

**Comment by asgraf** [comment]
I have tested [php-hammer-0.29.0-preview.3.zip](https://github.com/hammer-tools/php-hammer/files/13210415/php-hammer-0.29.0-preview.3.zip) and her are my findinds:

In case of `Test 1` i see no changes

In case of `Test 2`
`🔨 PHP Hammer: this method has an #[Override] on at least one method, but this method is not present in all classes that use this trait.` is correctly displayed inside trait but:
- selecting `Show incompatible classes` does nothing
- selecting `Show overrided methods` does nothing

**Comment by asgraf** [comment]
In regard to my previous post about `@mixin`
In case of traits `@mixin` usually points to some framework base class like `\Cake\ORM\Table`, `\Cake\Controller\Controller` or `\Cake\View\View` class, while traits themselves are intended to be applied to one of their subclasess like `UsersTable`, `PackagesTable`,  `UsersController`, `PackagesController`,  `AppView`, `CsvView` etc

So in  context of this ticket, when trait is not applied to any class, for purpose of override attribute you can assume that:
- #[\Override] is valid if method with same name exist in any class or interface pointed in `@mixin` tags (you can have more than one `@mixin` phpdoc tag in same class)
- #[\Override] is not valid if method with same name does not exist in any class or interface pointed in `@mixin` tags
- note that classes pointed in `@mixin` can also have `@mixin` tag themselves in their implementation (common in CakePHP tables, table class usualy have have multiple `@mixin` tags pointing to Behavior classes)

**Comment by rentalhost** [comment]
I made some improvements regarding this issue. Could you check if it's still being affected? If so, could you try creating a minimal code reproducing the problem, without relying on external projects?

**Comment by asgraf** [comment]
I have checked on my project and this is fixed for me

**Comment by rentalhost** [comment]
Nice!
