### ISSUE TITLE
Illegal `#[\Override]` error should not have a quick fix

### ISSUE THREAD

**Issue by asgraf** [hammer-tools/php-hammer#45]
In case of illegal `#[\Override]` attribute do not suggest quick fix by removing `#[\Override]`
Yes, removing `#[Override]` does silent the error, but does **NOT** fix underlying problem that parent method is missing.
Currently when you inspect whole project it is possible to remove all invalid `#[\Override]` attributes from whole project by accident by applying quickfix for all cases by single click 
I think removing `#[\Override]`  should be conscious and deliberate decision made case by case manually by programmer.
Not a quick-fix

Also error message should look something like this:
`🔨 PHP Hammer: [CurrentClassOrTraitName]::[methodName] is marked as an #[Override] and [ParentClassName]::[methodName] does not exist`

**Comment by asgraf** [comment]
Quick fix for removing `#[\Override]` can make sense in two scenarios:
- `#[\Override]` attached to private method
- `#[\Override]` attached to method of base class

**Comment by rentalhost** [comment]
Fixed by **98a75b54** (still not released).
