### ISSUE TITLE
Bug: `senseless call to empty parent::initialize()` false positive

### ISSUE THREAD

**Issue by asgraf** [hammer-tools/php-hammer#49]
```php
/**
 * @mixin A
 * This phpdoc tells static analyzers that methods and properties from class A are available here
 * (including someMethod)
 */
trait SomeTrait
{
    public function traitMethod($arg): void
    {
        //if you remove mixin phpdoc from this trait and remove `use SomeTrait;` from class C
        //phpstorm and static analyzers would complain about call to undefined method `someMethod`
        $this->someMethod($arg);
    }
}

class A
{
    public function initialize(array $config): void
    {
    }

    public function someMethod($arg): void
    {
        //implementation is not important in this example
    }
}

class B extends A
{
    #[\Override] public function initialize(array $config): void
    {
        //some logic but without parent call
        $this->someMethod(1);
        $this->someMethod(2);
        $this->someMethod(3);
    }
}

class C extends B
{
    use SomeTrait;
    public function initialize(array $config): void
    {
        parent::initialize($config);//🔨 PHP Hammer: senseless call to empty parent::initialize().
        //some extra logic
        $this->someMethod(4);
        $this->someMethod(5);
        $this->someMethod(6);
    }
}
```
As you can see parent call in class C from `C::initialize` to `B::initialize` is not senseless
Parent call in class from `B::initialize` to `A::initialize` would be senseless because `A::initialize` has empty body but that's not a case here

**Comment by rentalhost** [comment]
@asgraf I am not receiving this warning with your code.

![image](https://github.com/hammer-tools/php-hammer/assets/421851/22b86315-1bf7-4ae8-902f-43a7e2ff5823)

**Comment by asgraf** [comment]
This is probably related with https://github.com/hammer-tools/php-hammer/issues/50#issuecomment-1801528645

Because in this case `@mixin A` could be replaced by ` @method void someMethod($args)` for same effect

**Comment by rentalhost** [comment]
I could reproduce `@mixin A` case at 0.29.1, but second case is not reproducible anymore.

**Comment by asgraf** [comment]
Yes second case was fixed in #50

**Comment by asgraf** [comment]
My point was that you probably can reuse logic from #50
`@mixin SomeClassOrInterface` bassicaly bassicaly is same as creating @method for every method and and @property for every property in SomeClassOrInterface

**Comment by rentalhost** [comment]
In a way, something in this direction has been done. The JetBrains SDK is a bit confusing, and I had to hardcode to fix the issue, which applies to both the previous case and this current one.
