### ISSUE TITLE
Detect fake abstract methods to prevent false positive 'missing parent::... call'

### ISSUE THREAD

**Issue by tminich** [hammer-tools/php-hammer#50]
Sometimes libraries use for some reason or another what I would call a fake abstract method, a method that needs to be overridden by a child class is implemented but throws an exception (example: Laravel's `getFacadeAccessor` method of the Facade class).

Not sure how feasible this is, but it would be great if PHP Hammer could detect this and not suggest calling the parent method in this case.

**Comment by rentalhost** [comment]
Hey! Could you provide a simplified example case? This may have already been fixed, but some new features have not yet been uploaded to the Marketplace.

**Comment by tminich** [comment]
Sure, this would show the warning if I hadn't suppressed it.

```php
class Enum extends Facade
{
    /**
     * @return string
     * @noinspection MissingParentCallInspection
     */
    #[Override]
    protected static function getFacadeAccessor(): string
    {
        return EnumService::class;
    }

}
```

**Comment by asgraf** [comment]
Here is more clear example:
```php
/**
 * @method void beforeSave(EventInterface $event, Entity $entity, ArrayObject $options)
 * @method void afterSave(EventInterface $event, Entity $entity, ArrayObject $options)
 * @method void afterSaveCommit(EventInterface $event, Entity $entity, ArrayObject $options)
 * @method void beforeDelete(EventInterface $event, Entity $entity, ArrayObject $options)
 * @method void afterDelete(EventInterface $event, Entity $entity, ArrayObject $options)
 * @method void afterDeleteCommit(EventInterface $event, Entity $entity, ArrayObject $options)
 */
class A {
   public function save(Entity $entity, $options)
   {
   //implementation calls beforeSave, afterSave and afterSaveCommit methods if they exist
   }
   public function delete(Entity $entity, $options)
   {
   //implementation calls beforeDelete, afterDelete and afterDeleteCommit methods if they exist
   }
}

class B extends A
{
   public beforeSave(EventInterface $event, Entity $entity, ArrayObject $options): void
   {
   //parent call is invalid because there is no parent to call
   //#[Override] is also invalid because there is no parent to call
   }
}

**Comment by tminich** [comment]
That's a different, maybe/probably related, thing I think. In my case the parent function is implemented like this:
```php
class Facade {
    protected static function getFacadeAccessor()
    {
        throw new RuntimeException('Facade does not implement getFacadeAccessor method.');
    }
}
```

**Comment by asgraf** [comment]
I'm sorry, my issue is separate problem then

**Comment by asgraf** [comment]
@rentalhost as i noticed in post above this are 2 separate issues
your fix adressed issue that i reported but not @tminich issue
As i understand now issue reported by @tminich is that MissingParentCallInspection suggest calling parent that does only throw exception
It is logical that methods that only throw exception should not be suggested for parent call in that inspection

**Comment by rentalhost** [comment]
I fixed both issues. Now, methods that only throw exceptions will no longer require parent::call().
