### ISSUE TITLE
Cannot install PHP Hammer 0.29.0 on PhpStorm 2023.2.3

### ISSUE THREAD

**Issue by asgraf** [hammer-tools/php-hammer#51]
When trying manual installation of PHP Hammer 0.29.0 i get following error message
`Plugin 'PHP Hammer' (version '0.29.0') is not compatible with the current version of the IDE, because it requires build 233 or newer but the current build is PS-232.10072.32`

I would like to point out that `0.29.0-preview.3` version is installing without problems

Since im using JetBrains Gateway to connect to PhpStorm via JetBrains Client here are all relevant info:
```
JetBrains Gateway 2023.2.4
Build #GW-232.10203.10, built on October 24, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2038M
Cores: 8
```
```
JetBrains Client 2023.2.3
Build #JBC-232.10072.32, built on October 13, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
Controller in Remote Development (PS), direct control type: Lux
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
```
```
PhpStorm 2023.2.3
Build #PS-232.10072.32, built on October 13, 2023
Runtime version: 17.0.8.1+7-b1000.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.0-19-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
```

**Comment by asgraf** [comment]
Assuming this add-on accidentally requires Early Access Program build?

**Comment by rentalhost** [comment]
Exactly, support is aimed at EAP 233, while you are using stable 232 (2023.2.3). Support for limitations related to PHP 8.3 is only available in EAP and it is not possible to compile in previous versions. However, I will do a separate build without this distinction from PHP 8.3 until the official release of EAP.

**Comment by rentalhost** [comment]
The latest version will be compatible with 233, which is still in EAP, but I created an adapted version for 232 on the Releases page.
