### ISSUE TITLE
Feature Request: Simplify with spread operator intention

### ISSUE THREAD

**Issue by asgraf** [hammer-tools/php-hammer#6]
some build-in functions can be simplified by using spread operator
1) iterators:
```php
$arrayResult = iterator_to_array(someFunctionReturningIterator());
//can be simplified to
$arrayResult = [...someFunctionReturningIterator()];
```

2) array_merge:
```php
$arrayResult = array_merge($arrayVariable, someFunctionReturningArray()));
//can be simplified to
$arrayResult = [...$arrayVariable, ...someFunctionReturningArray()];
```
3) array_merge with static array arguments:
```php
$arrayResult = array_merge(['a' => 1, 'b' => 2], $arrayVar, ['c' => 3]);
//after_replacing array_merge we will get
$arrayResult = [...['a' => 1, 'b' => 2], ...$arrayVar, ...['c' => 3]];
//and this can be further simplified to
$arrayResult = ['a' => 1, 'b' => 2, ...$arrayVar, 'c' => 3];
```

It would be cool to have intention for that

**Comment by asgraf** [comment]
I would also like to point out bug that code below currently incorrectly triggers [Array unpacking can be simplified](https://github.com/hammer-tools/php-hammer/wiki/Inspections#array-unpacking-can-be-simplified)
```php
$variable = [...someFunctionReturningIterator()];
```
In this example `$variable` has type of array.
Applying [Array unpacking can be simplified](https://github.com/hammer-tools/php-hammer/wiki/Inspections#array-unpacking-can-be-simplified) fix would change  `$variable` type from array to `\Generator`

**Comment by rentalhost** [comment]
Thanks for the sugestion. My biggest question in this case is whether it's better to keep using the function instead of the spread (for ease of understanding / cognitive reading). 

Regarding performance, there is also some difference (positive):

* Example 1: spread is 3.5% faster;
* Example 2: spread is 14.5% faster;
* Example 3: spread is 15.0% faster;

So, I am in favor of this FR. I'll try to implement it today, along with the fix related to #7.

**Comment by asgraf** [comment]
> My biggest question in this case is whether it's better to keep using the function instead of the spread (for ease of understanding / cognitive reading).

I think code readability should be concern for separate plugin.
Plugin similar to `PHP Foldings` (which had no updates since 2018)

**Comment by rentalhost** [comment]
I'm checking some issues around here.

The [`iterator_to_array()`](https://www.php.net/manual/en/function.iterator-to-array.php) function, when using its second parameter (`bool $preserve_keys = true`) as `true` (_default_), will make the returned array have keys, according to what was sent via `yield`. However, the PHP spread in `Iterator` disregards the key:

```php
function test() {
    yield 'a' => 1;
    yield 'b' => 2;
}

iterator_to_array(test()) === [ 'a' => 1, 'b' => 2 ]
[ ... test() ] === [ 0 => 1, 1 => 2 ]
```

To get the same result, the must set `preserve_keys` to `false`.

While `array_merge()` we can have a more satisfactory result:

```php
<?php

$a = [ 'a' => 1 ];
$b1 = [ 'b' => 1 ];
$b2 = [ 'b' => 2 ];

var_dump(array_merge($a, $b1, $b2));
var_dump([...$a, ...$b1, ...$b2]);

// Both: [ 'a' => 1, 'b' => 2 ]
```

For now I will only handle `array_merge()` and `iterator_to_array()` when the second parameter is explicitly `false`. So I await your assessment on the matter, to see if we can do something about it.

**Comment by rentalhost** [comment]
**Implemented to version 0.21.0:** it takes about three days to be published on the market. But if you want, you can download it from **[Releases](https://github.com/hammer-tools/php-hammer/releases)**.

I've tried to implement `iterator_to_array()` support, but it's not fully spread compatible, even if it only assumes that `$preserve_keys` is `false`. But I added support for `array_merge()`.

**Comment by asgraf** [comment]
I never cared about keys when using `iterator_to_array` so a never even noticed.
So in that case when `false` is not explicitly provided i think it is safer stategy is to only offer optional quick fix intention on `iterator_to_array` without raising any inspection notices for that line

**Comment by rentalhost** [comment]
I usually also use the `iterator_to_array()` without considering the keys, but when it is necessary, the inspection ends up changing the behavior.

This plugin is _inspection-only_ for now. I don't know if I want that it have _intentions_ at the moment. But I will add to checklist.
