### ISSUE TITLE
Reporting false positives regarding unused local variables.

### ISSUE THREAD

**Issue by JSabelli-FDX** [hammer-tools/php-hammer#61]
Each local variable is nested in an if-elseif-else statement block, where they stow a query from a controller class function (if the conditional they're nested in is true). Before this, they are initialized as null outside of the if-elseif-else statement block. In both of these locations, they are being flagged by this plugin as unused. 

These are false positives because after the triggered local variables grab their queries, they all get returned in a view()

basic functionality example:
```
public function fruitView() {
    $foo = null;
    $bar = null;

    foreach (Input::get('fruit_names') as $key => $name) {
       if ($name == 'apple') {
           $foo = AppleController::getAppleQuery();
       } 
       elseif ($name == 'banana') {
           $bar = BananaController::getBananaQuery();
       }
    }

    return view('overview.fruits', [
       'foo' => $foo,
       'bar' => $bar
    ]);
}
```

The local variables in the return view() are not flagged as unused.

FYI: this is just a basic gutted example to highlight the tracing, usage, and position of the local variables.

**Comment by rentalhost** [comment]
Hello, thanks for your report.

However, I was unable to simulate the problem with the code provided. Could you take a screenshot of the error message that appears? Normally this plugin does not report unused variables, so I have doubts as to where in the plugin this check is performed.

On occasion, it is only reported that it is possible to replace the array declaration with the `compact()` function.

![image](https://github.com/hammer-tools/php-hammer/assets/421851/e9e4095c-9319-406f-b558-59b56c7bcc09)

**Comment by JSabelli-FDX** [comment]
Hi! Thanks for responding. Upon further speculation, you were correct. It is not being caused by this plugin, otherwise it would be labelled with the PHP Hammer identifier with the little hammer. It must be another plugin that is causing the false positive.
Thank you again for taking the time to reach out, it's greatly appreciated :)

> Hello, thanks for your report.
> 
> However, I was unable to simulate the problem with the code provided. Could you take a screenshot of the error message that appears? Normally this plugin does not report unused variables, so I have doubts as to where in the plugin this check is performed.
> 
> On occasion, it is only reported that it is possible to replace the array declaration with the `compact()` function.
> 
> ![image](https://private-user-images.githubusercontent.com/421851/331348351-e9e4095c-9319-406f-b558-59b56c7bcc09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NTAzNTQsIm5iZiI6MTcxNTk1MDA1NCwicGF0aCI6Ii80MjE4NTEvMzMxMzQ4MzUxLWU5ZTQwOTVjLTkzMTktNDA2Zi1iNTU4LTU5YjU2YzdiY2MwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QxMjQ3MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjE1MzNiMGFkZjk1ZmI5NGZkOTM1NmEzZmRjZDk2NDNjODJiNjhjMWQ1NTdlMjk0ZTJiMWNjN2YxYTljMTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gpj6VUihvbfq_buZt_nQ8aMVmZMPXj4zXAI_gAJrdGU)
