### ISSUE TITLE
Support PS-242.*

### ISSUE THREAD

**Issue by reedy** [hammer-tools/php-hammer#62]
```
Plugin 'PHP Hammer' (version '0.30.0') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is PS-242.10180.24
```

Thanks!

**Comment by reedy** [comment]
Yeah, for now :)

**Comment by laurinkeithdavis** [comment]
Some of us only use EAP versions. :)

**Comment by rentalhost** [comment]
Hey guys! I'll pay attention to this update this weekend. Thank you and sorry for the delay!

**Comment by laurinkeithdavis** [comment]
Beta is now released.

**Comment by rentalhost** [comment]
Folks, unfortunately, I won't be able to support version **2024.2**. IntelliJ has made many changes since the last version, and since I don't have advanced knowledge of their platform, I've only encountered one problem after another. They changed A LOT, and it would take a significant amount of time to make it compatible again. I haven't given up yet, but I'm not very confident.

**Comment by laurinkeithdavis** [comment]
Ugh, that sucks. I've compiled PhpStorm extensions in the past. If I can get set up to test it properly, maybe I can assist. That is, assuming you are open to contributions

**Comment by rentalhost** [comment]
@laurinkeithdavis That would be great! I'll send the current dev as far as I've gotten, but it still doesn't work. It will be as a temporary commit.

**Comment by raubv0gel** [comment]
FYI, PhpStorm
```
    Version: 2024.2
    Build: 242.20224.361
    12 August 2024
```
is released. [`https://www.jetbrains.com/phpstorm/download/#section=windows`](`https://www.jetbrains.com/phpstorm/download/#section=windows`)

**Comment by raubv0gel** [comment]
I can assist if the problems are about [https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html).

**Comment by rentalhost** [comment]
@raubv0gel Thanks! @laurinkeithdavis is trying to solve it, but like me, he is having problems regarding the test environment setup that seems to have been modified.

![image (1)](https://github.com/user-attachments/assets/8b00f84a-03fa-4c72-bd31-90cfdced7315)

**Comment by raubv0gel** [comment]
I’m trying tonight …

**Comment by raubv0gel** [comment]
Same:

![grafik](https://github.com/user-attachments/assets/65ac79f8-058e-4abc-bf76-4e30bb3dbb60)

**Comment by laurinkeithdavis** [comment]
Maybe related?

https://youtrack.jetbrains.com/issue/IDEA-354553/Unable-to-run-tests-using-Kotest-and-IntelliJ-IDEA-EAP-2024.2

**Comment by laurinkeithdavis** [comment]
Or better yet, this:

https://plugins.jetbrains.com/docs/intellij/tests-and-fixtures.html

![image](https://github.com/user-attachments/assets/56b29cbc-c73b-425f-8cfc-50b4f2a9033b)

**Comment by laurinkeithdavis** [comment]
> Or better yet, this:

No, it can't even find com.intellij.testFramework.fixtures, so that's not it.

**Comment by raubv0gel** [comment]
In 
![grafik](https://github.com/user-attachments/assets/186d0ba4-a5a1-46c6-8292-6785be6abc09)

I only see:
![grafik](https://github.com/user-attachments/assets/8cc674b4-280b-43ca-b7c5-c51ceb883da8)

but we need something like [https://github.com/JetBrains/intellij-community/tree/master/platform/testFramework/src/com/intellij/testFramework](https://github.com/JetBrains/intellij-community/tree/master/platform/testFramework/src/com/intellij/testFramework)

**Comment by raubv0gel** [comment]
Oh, maybe got:

![grafik](https://github.com/user-attachments/assets/a378beed-f07b-4c14-b1a8-64963f87e4b2)

![grafik](https://github.com/user-attachments/assets/0b250160-36aa-4419-9514-33046f8104a2)

We need to move  TestService.kt to test module:

![grafik](https://github.com/user-attachments/assets/37c927d6-c745-46af-9050-09abd078a02d)

**Comment by raubv0gel** [comment]
Shall I create a PR?

**Comment by rentalhost** [comment]
@raubv0gel That would be great if you can! Thanks!

**Comment by raubv0gel** [comment]
@rentalhost please feel free to merge or modify PR #63.

**Comment by raubv0gel** [comment]
@rentalhost you are welcome. Thanks for publishing 0.31.0, 😀.

**Comment by raubv0gel** [comment]
We should close this issue now. 😏
