### ISSUE TITLE
Feature request: Obsolete API Migration inspector

### ISSUE THREAD

**Issue by elomonaco** [hammer-tools/php-hammer#9]
PHP Inspector has this and it's really nice, it has a way to detect obsolete functions being used and to recommend you update to the newer api.

**Comment by rentalhost** [comment]
Thanks for the suggestion.

Could you give me some examples of Obsolete API? If my memory serves correctly, PhpStorm has metadata using @deprecated for some PHP functions.

**Comment by elomonaco** [comment]
so for example

```
mt_rand(10000,99999)
```

would be replaced with

```
random_int(10000, 99999)
```

maybe obsolete is a poor use of word, as you can still technically use it (and PHP hasn't done away with it) but mt_rand isn't cryptographically secure so maybe that's more of why php inspector was suggesting the change.

**Comment by rentalhost** [comment]
It's a good addition, but I would need to better understand what the possibilities are in this regard. Could you indicate an article citing these changes or a good reference?

I also need to know if these changes can affect the behavior if modified. In your example though, I believe it's a safe move.

**Comment by rentalhost** [comment]
**Implemented in version 0.22.0:**

Hello @elomonaco, the new **version 0.22.0** has just been released and is available for direct download from the **[Releases](https://github.com/hammer-tools/php-hammer/releases/tag/0.22.0)** page. This update will be available on the **[Jetbrains Market](https://plugins.jetbrains.com/plugin/19515-php-hammer)** in approximately three days if you prefer to wait.

**This version comes with some new features, now totaling 51 inspections:**

- Support for the **new PhpStorm 2023.2 EAP** (_minimum version from now on_);
- **Your suggestions:** inspection to suggest strict comparison when possible;
- **Your suggestions:** Inspection to suggest the use of non-deprecated functions (e.g., `mt_rand()` to `random_int()`);
- Additional feature: add missing _semicolon_ when saving a PHP file;
- Other minor improvements.

Thank you for taking the time to suggest these improvements and for patiently waiting for their implementation.
